<script type="text/javascript">
    (function () {
        document.getElementById("intersales_overheat_general_jsTrackingCode").readOnly = true;
    })();
    function getTrackingCode() {
        params = {
            validate_code: jQuery('#intersales_overheat_general_apiKey').val()
        };
        new Ajax.Request('<?php echo $this->getAjaxUrl() ?>', {
            parameters: params,
            onSuccess: function (data) {
                transport = data.transport;
                try {
                    var json = transport.responseText.evalJSON(true);
                    if (json.errorMessage != '') {
                        alert(json.errorMessage);
                        jQuery('#intersales_overheat_general_jsTrackingCode').val('');

                    } else {
                        jQuery('#intersales_overheat_general_jsTrackingCode').val(json.trackingCode);
                    }
                } catch (e) {
                    alert(e.message);
                }
            }
        });
    }
</script>
<button onclick="javascript:getTrackingCode(); return false;" class="scalable" type="button" id="<?php echo $this->getHtmlId() ?>">
    <span id="get_tracking_code_result"><?php echo $this->escapeHtml($this->getButtonLabel()) ?></span>
</button>
